spring.application.name=freelancer-backend

spring.datasource.url=jdbc:mariadb://localhost:3306/bd_freelancer?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=231171

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ClaveLocalDeDesarrolloFreelancer2026DebeCambiarse
app.jwt.expiration-minutes=480
